#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Sun Oct 21 02:36:33 2018

@author: barclaysskybar
"""

import cv2
import numpy as np
import matplotlib.pyplot as plt

img = cv2.imread('testfeature.jpg', 1)
img1 = cv2.imread('template.jpg', 1)

orb = cv2.ORB_create()
kp1, des1 = orb.detectAndCompute(img, None)
kp2, des2 = orb.detectAndCompute(img1, None)
bf = cv2.BFMatcher(cv2.NORM_HAMMING, crossCheck = True)
matches = bf.match(des1, des2)
matches = sorted(matches, key = lambda x:x.distance)
img2 = cv2.drawMatches(img, kp1, img1, kp2, matches[:5], None, flags = 2)  
plt.imshow(img2)
plt.show()

k = cv2.waitKey(5) & 0xFF
    
cv2.destroyAllWindows()